### ISSUE TITLE
Bring this module up to parity with the fargate module, specifically secrets

### ISSUE THREAD

**Issue by ericduvic** [umotif-public/terraform-aws-ecs-fargate-task-definition#11]
**What is the current behavior?**
Secrets aren't available in this module

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Not quite a bug, just feature request

**What is the expected behavior?**
Just like the addition to the fargate module, a variable is provided to populate secrets in this module as well.

**Comment by marcincuber** [comment]
@ericduvic thanks again for contribution. Release [2.1.0](https://github.com/umotif-public/terraform-aws-ecs-fargate-task-definition/tree/2.1.0) includes the changes
