### ISSUE TITLE
Setting repository_credentials causes "count" error on plan

### ISSUE THREAD

**Issue by omairvaiyani** [umotif-public/terraform-aws-ecs-fargate-task-definition#4]
*main.tf*
```tf
module "task_definition" {
  source  = "umotif-public/ecs-fargate-task-definition/aws"
  version = "~> 1.0" 
  enabled              = true
  ...
  repository_credentials = var.repository_credentials_secret_arn
  ...
}
```

*variables.tf*
```tf
variable "repository_credentials_secret_arn" {
  type     = string
}
```

```
The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

Error points to this resource within your module
```tf
resource "aws_iam_role_policy" "read_repository_credentials" {
  count = length(var.repository_credentials) != 0 && var.enabled ? 1 : 0

  name   = "${var.name_prefix}-read-repository-credentials"
  role   = aws_iam_role.execution[0].id
  policy = data.aws_iam_policy_document.read_repository_credentials.json
}
```

I can remove the error by manually removing `length(var.repository_credentials) != 0` - but of course that doesn't fit your desired interface, so any suggestions how to bypass it?

**Comment by marcincuber** [comment]
@omairvaiyani thanks for reporting the issue. I think this is a wrong use of length function inside the module. Any chances you could modify the module directly locally in .terraform/modules and replace the following:
```
count = length(var.repository_credentials) != 0 && var.enabled ? 1 : 0
```
with
```
count = var.repository_credentials != "" && var.enabled ? 1 : 0 
```
and let me know whether that fixed the issue?

**Comment by omairvaiyani** [comment]
That does not fix it I'm afraid, also that fix would not work for those who provide no value for `repository_credentials`

**Comment by marcincuber** [comment]
@omairvaiyani 
Again, thanks for raising an issue. New version 1.2.0 includes resolution to the issue you experienced. The behaviour and error is the correct one from terraform perspective. In the fix I introduced a new variable which will make conditional creation work properly.

please use the following
```
  create_repository_credentials_iam_policy = true
  repository_credentials                                  = aws_secretsmanager_secret.task_credentials.arn
```
